import re


SENTENCE_PATTERN = re.compile(r"[^.!?\n]+(?:[.!?]+(?=\s|$)|$)", re.S)
MAX_REASON_OPTIONS = 10
TARGET_REASON_OPTIONS = 5
STREAM_TOKEN_DELAY_SECONDS = 0.2
STREAMING_TEMPERATURE = 0.9
REPLACEMENT_TEMPERATURE = 1.0
PROFILE_MEMORY_TEMPERATURE = 0.3
MAX_REPLACEMENT_WORDS = 45
